DELETE FROM UiTextDict;

INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.btn.new_piece','New piece','Новый кусок','F1');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.btn.open_card','Open card','Открыть карточку','F1');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.btn.reset','Reset','Сброс','F1');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.caption','Scrap pieces registry','Реестр кусков','F1');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.col.area','Area, mm2','Площадь, мм2','F1 grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.col.inventoryTag','Inventory tag','Инв. метка','F1 grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.col.location','Storage','Хранение','F1 grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.col.material','Material','Материал','F1 grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.col.nap','Nap angle, deg','Угол ворса, deg','F1 grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.col.quality','Quality','Качество','F1 grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.col.status','Status','Статус','F1 grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.col.updatedAt','Updated at','Обновлено','F1 grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.filter.find','Find inventory tag','Поиск по инв. метке','F1 filters');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.filter.location','Storage','Хранение','F1 filters');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.filter.material','Material','Материал','F1 filters');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.filter.status','Status','Статус','F1 filters');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f1.section.list','Pieces list','Список кусков','F1 sections');

INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.btn.contour_visual','Contour view','Контур (визуально)','F2 card');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.caption','Scrap piece card','Карточка куска','F2 card');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.col.areaMm2','Area, mm2','Площадь, мм2','F2 card fields');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.col.bboxHeightMm','Bounds height, mm','Высота габарита, мм','F2 card fields');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.col.bboxWidthMm','Bounds width, mm','Ширина габарита, мм','F2 card fields');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.col.createdAt','Created at','Создано','F2 card fields');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.col.inventoryTag','Inventory tag','Инв. метка','F2 card fields');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.col.materialId','Material','Материал','F2 card fields');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.col.maxSpanMm','Max span, mm','Макс. размах, мм','F2 card fields');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.col.napDirectionDeg','Nap angle, deg','Угол ворса, deg','F2 card fields');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.col.note','Note','Комментарий','F2 card fields');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.col.scrapQuality','Quality','Качество','F2 card fields');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.col.scrapStatus','Status','Статус','F2 card fields');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.col.storageLocationId','Location','Локация','F2 card fields');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.col.updatedAt','Updated at','Обновлено','F2 card fields');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.preview.btn.open','Open preview','Открыть превью','F2 card preview');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.preview.btn.refresh','Refresh only','Только обновить','F2 card preview');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.preview.mode','Mode','Режим','F2 card preview');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.preview.normalize','Normalize nap','Нормализовать ворс','F2 card preview');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.preview.output','Status / path','Статус / путь','F2 card preview');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.preview.section','Contour preview','Превью контура','F2 card preview');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.section.operations','Operations','Операции','F2 card sections');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('sf1.caption','SF1 - ScrapPiece list','SF1 - Список кусков','Forms');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('r1.caption','R1 Pick List','R1 Лист отбора','Reports');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('r2.caption','R2 Traceability','R2 Трассируемость','Reports');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.section.system','System','Системные поля','F2 card sections');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.card.section.usage','Usage history','История использования','F2 card sections');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_json.caption','Contour (JSON)','Контур (JSON)','F2 contour');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_preview.btn.refresh','Refresh','Обновить','F2 contour preview');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_preview.caption','Contour preview','Превью контура','F2 contour preview');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_preview.col.areaMm2','Area, mm2','Площадь, мм2','F2 contour preview');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_preview.col.bboxHeightMm','Bounds height, mm','Высота габарита, мм','F2 contour preview');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_preview.col.bboxWidthMm','Bounds width, mm','Ширина габарита, мм','F2 contour preview');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_preview.col.inventoryTag','Inventory tag','Инв. метка','F2 contour preview');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_preview.col.maxSpanMm','Max span, mm','Макс. размах, мм','F2 contour preview');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_preview.col.napDirectionDeg','Nap angle, deg','Угол ворса, deg','F2 contour preview');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_preview.label.preview','Preview','Превью','F2 contour preview');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_visual.btn.redraw','Redraw','Перерисовать','F2 contour visual');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_visual.caption','Contour visual','Контур (визуально)','F2 contour visual');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_visual.col.areaMm2','Area, mm2','Площадь, мм2','F2 contour visual');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_visual.col.bboxHeightMm','Bounds height, mm','Высота габарита, мм','F2 contour visual');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_visual.col.bboxWidthMm','Bounds width, mm','Ширина габарита, мм','F2 contour visual');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_visual.col.inventoryTag','Inventory tag','Инв. метка','F2 contour visual');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_visual.col.maxSpanMm','Max span, mm','Макс. размах, мм','F2 contour visual');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_visual.col.napDirectionDeg','Nap angle, deg','Угол ворса, deg','F2 contour visual');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_visual.mode.label','Mode','Режим','F2 contour visual');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_visual.mode.piece','Piece (normalized)','Кусок (нормализ.)','F2 contour visual');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_visual.mode.scana3','Scan A3 (original)','Скан A3 (исходное)','F2 contour visual');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_visual.normalize.label','Normalization','Нормализация','F2 contour visual');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f2.contour_visual.output.label','Output','Вывод','F2 contour visual');

INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f3.btn.reserve','Reserve','Зарезервировать','F3');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f3.btn.release','Release reservation','Снять резерв','F3');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f3.caption','Reservation','Резервирование','F3');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f3.col.inventoryTag','Inventory tag','Инв. метка','F3 grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f3.col.note','Note','Комментарий','F3 grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f3.col.reservedBy','Reserved for','Резерв под','F3 grid');

INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f4.btn.apply','Apply','Применить','F4');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f4.btn.clear','Clear','Очистить','F4');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f4.caption','Usage history','История использования','F4');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f4.col.fragmentId','Fragment','Фрагмент','F4 grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f4.col.inventoryTag','Inventory tag','Инв. метка','F4 grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f4.col.layoutRunId','Layout run','Запуск выкладки','F4 grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f4.col.offsetXmm','Offset X, mm','Смещение X, мм','F4 grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f4.col.offsetYmm','Offset Y, mm','Смещение Y, мм','F4 grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f4.col.rotationDeg','Rotation, deg','Поворот, deg','F4 grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('f4.filter.inventoryTag','Inventory tag','Инв. метка','F4 filters');

INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('sf2.tx.caption','Transactions','Операции по куску','SF2 tx');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('sf2.tx.col.after','After','Стало','SF2 tx grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('sf2.tx.col.before','Before','Было','SF2 tx grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('sf2.tx.col.inventoryTag','Inventory tag','Инв. метка','SF2 tx grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('sf2.tx.col.sourceRef','Source ref','Основание','SF2 tx grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('sf2.tx.col.transAt','Date/time','Дата/время','SF2 tx grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('sf2.tx.col.transType','Type','Тип','SF2 tx grid');

INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('sf2.usage.caption','Usage','Использование','SF2 usage');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('sf2.usage.col.fragmentId','Fragment','Фрагмент','SF2 usage grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('sf2.usage.col.inventoryTag','Inventory tag','Инв. метка','SF2 usage grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('sf2.usage.col.layoutRunId','Layout run','Запуск выкладки','SF2 usage grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('sf2.usage.col.offsetXmm','Offset X, mm','Смещение X, мм','SF2 usage grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('sf2.usage.col.offsetYmm','Offset Y, mm','Смещение Y, мм','SF2 usage grid');
INSERT INTO UiTextDict (captionKey, textEn, textRu, [context]) VALUES ('sf2.usage.col.rotationDeg','Rotation, deg','Поворот, deg','SF2 usage grid');
